apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: default
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        {{- if .Values.keyVault.enabled }}
        env:
        - name: {{ .Values.keyVault.envName }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-keyvault-secret
              key: {{ .Values.keyVault.secretName }}
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      {{- if .Values.keyVault.enabled }}
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Release.Name }}-keyvault-spc
      {{- end }} 