apiVersion: v1
kind: ServiceAccount
metadata:
  name: kv-reader-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "97746289-72e0-4c20-a1a1-ef10727b31cd"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kv-reader-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "97746289-72e0-4c20-a1a1-ef10727b31cd"

---

apiVersion: v1
kind: Pod
metadata:
  name: keyvault-demo
  namespace: default
spec:
  serviceAccountName: kv-reader-sa
  containers:
    - name: demo-container
      image: nginx
      command: ["/bin/sh", "-c", "echo 'Secrets are mounted at /mnt/secrets-store. Pod is now running.' && sleep 3600"]
      volumeMounts:
        - name: secrets-store-volume
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-volume
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-postgres" 