apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-postgres
  namespace: default
spec:
  provider: azure
  parameters:
    useWorkloadIdentity: "true"
    keyvaultName: "dev-llm-keyvault"
    clientID: "5e36c3f5-4aa4-465d-a1e3-e749301d36b5" # Managed Identity Client ID
    tenantId: "1a20a08a-cff0-479f-87e5-e4027d22cdbc" # Managed Identity Tenant ID

    objects: |
      array:
        - |
          objectName: postgresql-admin-password
          objectType: secret
        - |
          objectName: postgresql-admin-username
          objectType: secret
        - |
          objectName: postgresql-database
          objectType: secret
        - |
          objectName: postgresql-host
          objectType: secret
        - |
          objectName: postgresql-port
          objectType: secret