{{- if .Values.litellm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openwebui-stack.fullname" . }}-litellm-config
  labels:
    {{- include "openwebui-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
data:
  config.yaml: |
    model_list:
      - model_name: {{ .Values.ollama.model | quote }}
        litellm_params:
          model: ollama/{{ .Values.ollama.model }}
          api_base: http://{{ include "openwebui-stack.fullname" . }}-ollama:{{ .Values.ollama.service.port }}
    litellm_settings:
      master_key: "env/LITELLM_MASTER_KEY"
{{- end }}