apiVersion: v1
kind: Service
metadata:
  name: {{ include "openwebui-stack.fullname" . }}-openwebui
  labels:
    {{- include "openwebui-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui
spec:
  type: {{ .Values.openwebui.service.type }}
  ports:
    - port: {{ .Values.openwebui.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "openwebui-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui